### ISSUE TITLE
kevin. Unable to change order status. Please check whether signature is correct.

### ISSUE THREAD

**Issue by ssinisalo** [getkevin/kevin-woocommerce#10]
After upgrading to 2.2.0 (from very first version) Kevin plugin cannot change order status and is eventually cancelled. Although transaction appears in kevin dashboard. 

Downgraged to 2.1.6 and  everything is normal again.

**Comment by saltanovas** [comment]
@ssinisalo that's because you have entered your endpoint secret incorrectly in the module settings ;)

**Comment by ssinisalo** [comment]
@saltanovas  Thank you, but should you mention it somewhere in here or in plugin installation that you suddenly need another code when installing new version. Or ignore it if its empty?  I Checked kevin console and there is no easy way to get it. I dont have rights to modify my existing project. I should to make new project, fill KYC again and then maybe I'll find it somewhere.

**Comment by saltanovas** [comment]
@ssinisalo although our Dashboard does not provide the option to view project credentials at the moment, you should contact our support team at help@kevin.eu. They will remind and send you your `Endpoint Secret`.
