### ISSUE TITLE
Warnings in error log

### ISSUE THREAD

**Issue by mch0lic** [getkevin/kevin-woocommerce#9]
2022/02/16 10:16:43 [error] 2019#2019: *348 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined property: WC_Gateway_GetKevin::$projectSettings in /mnt/project/site/web/app/plugins/kevin-woocommerce/includes/class-wc-getkevin-gateway.php on line 178

PHP message: PHP Notice:  Undefined property: WC_Gateway_GetKevin::$projectSettings in /mnt/project/site/web/app/plugins/kevin-woocommerce/includes/class-wc-getkevin-gateway.php on line 181

PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /mnt/project/site/web/app/plugins/kevin-woocommerce/includes/class-wc-getkevin-gateway.php on line 181

PHP message: PHP Notice:  Undefined property: WC_Gateway_GetKevin::$projectSettings in /mnt/project/site/web/app/plugins/kevin-woocommerce/includes/class-wc-getkevin-gateway.php on line 200

PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /mnt/project/site/web/app/plugins/kevin-woocommerce/includes/class-wc-getkevin-gateway.php on line 200

**Comment by saltanovas** [comment]
@mch0lic could you please confirm that our changes fixed your installation errors?

**Comment by mch0lic** [comment]
Confirm fixed.
